permalink: none
exclude: [ "sass", "CNAME", "config.rb", "LICENSE", "README.md", "_assets", "Gemfile", "Gemfile.lock", "rakefile" ]


prose:
 rooturl: "_posts/"
 metadata: 
  "_posts/exhibits": |
   layout: default
   category: exhibit
   title: "stories"
   section: "La secci√≥n a la que pertenece este exhibit"
  "_posts/sections": |
   layout: default
   category: section
   title: "Stories by Tom Hackshaw"
title: stories
author: tomhackshaw

